site_name: protolink
site_description: "Agent-to-agent communication framework for interoperable agent systems"
repo_url: https://github.com/nMaroulis/protolink
repo_name: nMaroulis/protolink


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nMaroulis/protolink
    - icon: fontawesome/solid/book
      link: https://pypi.org/project/protolink/
  generator: false
  copyright:
    text: "Â© 2025 Nikolaos Maroulis. MIT licensed."

theme:
  name: material
  logo: assets/logo_sm.png
  favicon: assets/logo_sm.png
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - navigation.footer
    - navigation.expand
    - navigation.top

markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - meta

nav:
  - Overview:
      - Home: index.md
      - Concept: concept.md
      - Getting Started: getting-started.md
  - API Reference:
      - Agents: agents.md
      - LLMs: llms.md
      - Models: models.md
      - Registry: registry.md
      - Tools: tools.md
      - Transports: transports.md
      - Types: types.md
  - Examples:
      - Examples: examples.md
  - Resources:
      - Relevant Projects: relevant.md
